apiVersion: v2
name: argo-cd
description: Playing around with ArgoCD settings using a Helm chart

type: application

version: 1.0.0

dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 4.9.16
